# Generated by Django 4.0.4 on 2022-06-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateImpactsTypeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='name')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='section')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTypeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LevelDisasterImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('start_year', models.IntegerField(blank=True, default=0, verbose_name='start year')),
                ('lifetime', models.IntegerField(blank=True, default=0, verbose_name='lifetime')),
                ('discount_rate', models.FloatField(blank=True, default=0, verbose_name='discount rate')),
            ],
            options={
                'ordering': ('-start_year',),
            },
        ),
        migrations.CreateModel(
            name='ProjectInvestmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioInvestmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='value')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_project', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='value')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.projectinvestmentcost')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.scenario')),
                ('type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.investmenttypevalue')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='optimistic_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimistic_scenario', to='baseapp.scenario'),
        ),
        migrations.AddField(
            model_name='project',
            name='pesimistic_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesimistic_scenario', to='baseapp.scenario'),
        ),
        migrations.CreateModel(
            name='ChangeDisasterImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('return_period', models.IntegerField(blank=True, default=0, verbose_name='return_period')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='value')),
                ('disaster_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.disasterimpact')),
                ('level_disaster_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.leveldisasterimpact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
                ('type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.climateimpactstypevalue')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeClimateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_project', models.BooleanField(default=False)),
                ('impact', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='value')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.projectinvestmentcost')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
                ('type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.climateimpactstypevalue')),
            ],
        ),
    ]
