# Generated by Django 4.0.4 on 2022-06-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_scenariodata_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariodata',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.projectinvestmentcost'),
        ),
        migrations.CreateModel(
            name='SensitivityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('disaster_impact_name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='section')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='value')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
            ],
        ),
    ]
