# Generated by Django 4.0.4 on 2022-06-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_scenariodata_cost_sensitivityanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDisasterImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.disasterimpact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
            ],
        ),
    ]
