# Generated by Django 4.0.4 on 2022-06-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_rename_name_projectsdisasterimpact_disaster_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changedisasterimpact',
            name='return_period',
        ),
    ]
