# Generated by Django 4.0.4 on 2022-06-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_remove_changedisasterimpact_return_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivityanalysis',
            name='disaster_impact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='disaster impact'),
        ),
        migrations.CreateModel(
            name='CalculationForGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_pessimism', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('level_of_climate_impact', models.IntegerField(blank=True, default=0, verbose_name='year')),
                ('value', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=15, verbose_name='value')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
            ],
        ),
    ]
