# Generated by Django 4.0.4 on 2022-06-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_sensitivityanalysis_disaster_impact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_calculate',
            field=models.BooleanField(default=False),
        ),
    ]
