# Generated by Django 4.0.4 on 2022-06-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_project_calculated_project_is_calculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='section')),
                ('type_value', models.CharField(blank=True, max_length=150, verbose_name='type_value')),
                ('level', models.IntegerField(blank=True, default=0, verbose_name='level')),
                ('value', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=15, verbose_name='value')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.project')),
            ],
        ),
    ]
