# Generated by Django 4.0.4 on 2022-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baseline_pessimism',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7, verbose_name='Baseline scenario (0%=optimistic, 100%=pessimistic)'),
        ),
        migrations.AddField(
            model_name='project',
            name='level_of_climate_impact',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7, verbose_name='Climate change impact (0%=no/low impact, 100%=high impact)'),
        ),
        migrations.AddField(
            model_name='project',
            name='threshold_below_for_risk',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7, verbose_name='Threshold below which risk is unaccetable (NPV)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=7, verbose_name='discount rate'),
        ),
    ]
